### ISSUE TITLE
Inaccurate data

### ISSUE THREAD

**Issue by dtmilano** [android-ui-testing/Cookbook#46]
You mentioned:
"*Although it has become very popular recently, screenshot testing has been possible on Android since 2015.*"

in one of your articles but that's not accurate as screenshot testing has been around on android for much longer:
- https://dtmilano.blogspot.com/2011/04/monkeyrunner-visual-image-comparison.html (april 2011)
- https://github.com/dtmilano/AndroidViewClient/blob/master/src/com/dtmilano/android/viewclient.py#L4458 (distance between different View trees)

**Comment by dtmilano** [comment]
The document you are creating is a great reference for testing. Thanks for doing and maintaining it.

**Comment by sergio-sastre** [comment]
@dtmilano Thanks for sharing those links, I was completely unaware of them. I will update the documentation accordingly and add you as a reviewer :)

**Comment by NoNews** [comment]
Thank you @dtmilano , it's been fixed here #47
